{
    "name": "Enterprise Security Authentication",
    "version": "17.0.1.2.0",
    "category": "Technical/Security",
    "summary": "Advanced authentication security, session tracking, and audit controls.",
    "author": "Naim Reza",
    "depends": ["base", "mail", "web"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/security_config_data.xml",
        "data/mail_template_data.xml",
        "data/cron.xml",
        "views/auth_otp_login_templates.xml",
        "views/auth_security_config_views.xml",
        "views/auth_login_attempt_views.xml",
        "views/auth_user_session_views.xml",
        "views/auth_audit_log_views.xml",
        "views/auth_otp_code_views.xml",
        "views/auth_security_test_wizard_views.xml",
        "views/res_users_views.xml",
        "views/menu.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "enterprise_security_authentication/static/src/scss/security_test_console.scss",
        ],
    },
    "installable": True,
    "application": True,
    "license": "LGPL-3",
}
