from datetime import timedelta
from hashlib import sha256

from odoo import fields, models


class AuthSecurityTestWizard(models.TransientModel):
    _name = "auth.security.test.wizard"
    _description = "Security Test Console"

    user_id = fields.Many2one(
        "res.users",
        string="Test User",
        required=True,
        default=lambda self: self.env.user,
    )
    login = fields.Char(required=True, default=lambda self: self.env.user.login)
    ip_address = fields.Char(required=True, default="127.0.0.1")
    user_agent = fields.Text(default="Enterprise Security Test Console")
    device_name = fields.Char(default="Test Browser")
    location = fields.Char(default="Local Test")
    failed_attempt_count = fields.Integer(default=3)
    mark_locked = fields.Boolean(default=True)
    otp_code = fields.Char(default="123456")
    notes = fields.Text(
        default=(
            "Generate sample security records, then check Monitoring and Configuration "
            "menus to confirm the backend UI is working."
        )
    )

    def _notify(self, title, message, notification_type="success"):
        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": title,
                "message": message,
                "sticky": False,
                "type": notification_type,
            },
        }

    def _test_marker(self):
        return "[TEST DATA]"

    def _login(self):
        return self.login or self.user_id.login or self.user_id.email

    def action_generate_failed_attempts(self):
        self.ensure_one()
        now = fields.Datetime.now()
        count = max(self.failed_attempt_count, 1)
        values_list = []
        for index in range(count):
            values = {
                "login": self._login(),
                "user_id": self.user_id.id,
                "company_id": self.env.company.id,
                "ip_address": self.ip_address,
                "user_agent": self.user_agent,
                "attempted_at": now - timedelta(minutes=count - index),
                "success": False,
                "failure_reason": "%s Invalid password from test console" % self._test_marker(),
            }
            if self.mark_locked and index == count - 1:
                values["locked_until"] = now + timedelta(minutes=30)
                values["failure_reason"] = "%s Account locked by test console" % self._test_marker()
            values_list.append(values)

        self.env["auth.login.attempt"].create(values_list)
        return self._notify("Test Data Created", "%s failed login attempts were generated." % count)

    def action_generate_successful_login(self):
        self.ensure_one()
        self.env["auth.login.attempt"].create(
            {
                "login": self._login(),
                "user_id": self.user_id.id,
                "company_id": self.env.company.id,
                "ip_address": self.ip_address,
                "user_agent": self.user_agent,
                "success": True,
            }
        )
        self.env["auth.audit.log"].log_event(
            "login_success",
            user=self.user_id,
            severity="info",
            description="%s Successful login generated by test console" % self._test_marker(),
            ip_address=self.ip_address,
            user_agent=self.user_agent,
        )
        return self._notify("Test Data Created", "A successful login and audit log were generated.")

    def action_create_active_session(self):
        self.ensure_one()
        token_seed = "%s-%s-%s" % (self.user_id.id, self.ip_address, fields.Datetime.now())
        self.env["auth.user.session"].create(
            {
                "user_id": self.user_id.id,
                "session_token": "test-%s" % sha256(token_seed.encode()).hexdigest()[:24],
                "ip_address": self.ip_address,
                "user_agent": self.user_agent,
                "device_name": self.device_name,
                "location": self.location,
                "active": True,
            }
        )
        return self._notify("Test Data Created", "An active user session was generated.")

    def action_create_audit_logs(self):
        self.ensure_one()
        audit_model = self.env["auth.audit.log"]
        events = [
            ("login_failure", "warning", "Failed login generated by test console"),
            ("account_locked", "critical", "Account lock generated by test console"),
            ("password_reset_requested", "info", "Password reset audit generated by test console"),
            ("ip_restricted", "warning", "IP restriction event generated by test console"),
        ]
        for event_type, severity, description in events:
            audit_model.log_event(
                event_type,
                user=self.user_id,
                severity=severity,
                description="%s %s" % (self._test_marker(), description),
                ip_address=self.ip_address,
                user_agent=self.user_agent,
            )
        return self._notify("Test Data Created", "%s audit log events were generated." % len(events))

    def action_create_otp_code(self):
        self.ensure_one()
        code = self.otp_code or "123456"
        self.env["auth.otp.code"].create(
            {
                "user_id": self.user_id.id,
                "purpose": "login",
                "delivery_channel": "email",
                "code_hash": sha256(code.encode()).hexdigest(),
                "expires_at": fields.Datetime.now() + timedelta(minutes=10),
                "ip_address": self.ip_address,
                "user_agent": self.user_agent,
            }
        )
        self.env["auth.audit.log"].log_event(
            "otp_sent",
            user=self.user_id,
            severity="info",
            description="%s Email OTP generated by test console" % self._test_marker(),
            ip_address=self.ip_address,
            user_agent=self.user_agent,
        )
        return self._notify("Test Data Created", "An email OTP record was generated.")

    def action_generate_all(self):
        self.ensure_one()
        self.action_generate_failed_attempts()
        self.action_generate_successful_login()
        self.action_create_active_session()
        self.action_create_audit_logs()
        self.action_create_otp_code()
        return self._notify("Test Data Created", "Full security test dataset generated.")

    def action_clear_test_data(self):
        self.ensure_one()
        marker = self._test_marker()
        login = self._login()
        self.env["auth.login.attempt"].search(
            [
                ("login", "=", login),
                ("ip_address", "=", self.ip_address),
                ("failure_reason", "ilike", marker),
            ]
        ).unlink()
        self.env["auth.user.session"].search(
            [
                ("user_id", "=", self.user_id.id),
                ("ip_address", "=", self.ip_address),
                ("session_token", "ilike", "test-"),
            ]
        ).unlink()
        self.env["auth.audit.log"].search(
            [
                ("user_id", "=", self.user_id.id),
                ("ip_address", "=", self.ip_address),
                ("description", "ilike", marker),
            ]
        ).unlink()
        self.env["auth.otp.code"].search(
            [
                ("user_id", "=", self.user_id.id),
                ("ip_address", "=", self.ip_address),
                ("user_agent", "=", self.user_agent),
            ]
        ).unlink()
        return self._notify("Test Data Cleared", "Generated records for this user and IP were removed.")
